apiVersion: apps/v1
kind: Deployment
metadata:
  name: incident-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: incident-app
  template:
    metadata:
      labels:
        app: incident-app
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: incident-app
          image: incidentplatformacr.azurecr.io/incident-service-management:1.0
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: incident-data
              mountPath: /app/data
      volumes:
        - name: incident-data
          persistentVolumeClaim:
            claimName: incident-data